"""
Django settings for all_test project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=^frusgla*6_-&7f5k9vboie26!pxd^8y&6ilfj#60anujr+e)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'all_test',
    'django_apscheduler',  # 定时任务
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 定时任务
CRONJOBS = [
    # 每5分钟执行一次生成主页静态文件
    ('*/5 * * * *', 'all_test.cronjobs.monitor.monitor', '>>crontab.log')
]

ROOT_URLCONF = 'all_test.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['appfront/dist'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'all_test.wsgi.application'

# Add for vue.js
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "../appfront/dist/static")
]
# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
     # 'default': {
     #    'ENGINE': 'django.db.backends.mysql',
     #    'NAME': 'testcenter',
     #    'USER': 'tester',
     #    'PASSWORD': 'test@123',
     #    'HOST': '10.124.26.94',
     #    'PORT': '3306',
     #    'OPTIONS': {
     #        "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
     #    }
     # }
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'testcenter',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

# LANGUAGE_CODE = 'en-us'
#
# TIME_ZONE = 'UTC'
LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'


ZTDS_SYSTEM = {
    'BASE_INFO': {
        'ip': '10.124.26.126',
        'username': 'administrator',
        'password': 'tsyzcmhhh0.'
    },
    'REMOTE_INFO': {
      'ip': '10.124.23.224',
      'username': 'administrator',
      'password': 'mp'
    },
    'TSY_TEST': {
        'svn_position': 'file:///D:/SVN/svntest/SVN_test',
        'project_position': 'C:\\Users\\TSY\\workspace\\test',
    },
    'WMS_TEST': {
        'svn_position': 'svn://192.168.0.179/zt-ecommercial/projects/wms/wms-dev/wms',
        'project_position': 'D:\hnzt\ztdev\projects\wms-test',
        'svn_username': 'liuliangjin',
        'svn_password': 'svn.com'
    },
    'CRM_TEST': {
        'svn_position': 'svn://192.168.0.179/zt-ecommercial/projects/CRM-DEV/crm',
        'project_position': 'D:/hnzt/ztdev/projects/crm-test',
        'svn_username': 'liuliangjin',
        'svn_password': 'svn.com'
    },
    'PRM_TEST': {
        'svn_position': 'svn://192.168.0.179/zt-ecommercial/projects/RISK/RISK-DEV/riskmg',
        'project_position': 'D:/hnzt/ztdev/projects/prm_Test',
        'svn_username': 'liuliangjin',
        'svn_password': 'svn.com'
    },
    'EC_TEST': {
        'svn_position': 'svn://192.168.0.179/zt-ecommercial/projects/EC/applications/steel/web',
        'project_position': '"D:/hnzt/ztdev/projects/ec-steel-test"',
        'svn_username': 'liuliangjin',
        'svn_password': 'svn.com'
    },
    'WMS_STAGE': {
        'svn_position': 'svn://192.168.0.179/zt-ecommercial/projects/wms/wms-dev/',
        'project_position': '"D:\stage all\wms-stage"',
        'svn_username': 'liuliangjin',
        'svn_password': 'svn.com'
    }
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['console'],
            'propagate': True,
            'level': 'DEBUG',
        },
    }
}